import {
  ContractBody,
  PaymentTypeParam,
  StudyFormParam,
  StudyTypeParam,
} from '@/lib/api/contract/types/ContractBody';

export const initialValues: ContractBody = {
  entrant: {
    firstName: '',
    middleName: undefined,
    lastName: '',
    passportSeries: undefined,
    passportNumber: '',
    passportInstitute: '',
    passportDate: '',
    address: '',
    settlement: '',
    idCode: undefined,
    phoneNumber: '',
    email: '',
    index: '',
  },
  representative: {
    firstName: '',
    middleName: undefined,
    lastName: '',
    passportSeries: undefined,
    passportNumber: '',
    passportInstitute: '',
    passportDate: '',
    address: '',
    settlement: '',
    idCode: undefined,
    phoneNumber: '',
    email: '',
    index: '',
  },
  meta: {
    studyType: '',
    studyForm: '',
    paymentType: undefined,
    speciality: '',
    isToAdmission: false,
  },
};
