// import { Metadata } from 'next';

// import { Inter } from 'next/font/google';
import '@/styles/reset.scss';
import '@/styles/typography.scss';
import '@/styles/global-styles.scss';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'FICT Advisor',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
